language: objective-c
osx_image: xcode7.3
script:
- xcodebuild build test -workspace ManagedObjectAdapter.xcworkspace -scheme ManagedObjectAdapter -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' 
